--- Ships
Raft1:
    id  : "raft-1#"
    assetName : "Raft1"
    slopeSpeed : 15
    maxSuppliesCount: 250
    maxSailorsCount: 1
    marketPrice: 1
    rotationSpeed: 15
    movementSpeed: 5
    maxHealth: 250
