--- Ships
Raft1:
    id  : "raft-1#"
    assetName : "Raft-1"
    slopeSpeed : 15
    absSpeed : 10
    maxSuppliesCount: 250
    maxSailorsCount: 1
    marketPrice: 1
    rotationSpeed: 15
    movementSpeed: 15
    maxHealth: 250
