// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var SailorIO = SailorIO || {};

/**
 * @const
 * @namespace
 */
SailorIO.ClientInputModel = SailorIO.ClientInputModel || {};

/**
 * @enum
 */
SailorIO.ClientInputModel.ClientEventTypes = {
  NONE: 0,
  GetWorldInfo: 1,
  NewPlayer: 2,
  BuyNewShip: 3,
  SailShip: 4
};

/**
 * @enum
 */
SailorIO.ClientInputModel.ShipTypes = {
  RAFT1: 0
};

/**
 * @constructor
 */
SailorIO.ClientInputModel.BuyNewShip = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SailorIO.ClientInputModel.BuyNewShip}
 */
SailorIO.ClientInputModel.BuyNewShip.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SailorIO.ClientInputModel.BuyNewShip=} obj
 * @returns {SailorIO.ClientInputModel.BuyNewShip}
 */
SailorIO.ClientInputModel.BuyNewShip.getRootAsBuyNewShip = function(bb, obj) {
  return (obj || new SailorIO.ClientInputModel.BuyNewShip).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {SailorIO.ClientInputModel.ShipTypes}
 */
SailorIO.ClientInputModel.BuyNewShip.prototype.ship = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {SailorIO.ClientInputModel.ShipTypes} */ (this.bb.readInt8(this.bb_pos + offset)) : SailorIO.ClientInputModel.ShipTypes.RAFT1;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SailorIO.ClientInputModel.BuyNewShip.startBuyNewShip = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {SailorIO.ClientInputModel.ShipTypes} ship
 */
SailorIO.ClientInputModel.BuyNewShip.addShip = function(builder, ship) {
  builder.addFieldInt8(0, ship, SailorIO.ClientInputModel.ShipTypes.RAFT1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SailorIO.ClientInputModel.BuyNewShip.endBuyNewShip = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SailorIO.ClientInputModel.SailShip = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SailorIO.ClientInputModel.SailShip}
 */
SailorIO.ClientInputModel.SailShip.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SailorIO.ClientInputModel.SailShip=} obj
 * @returns {SailorIO.ClientInputModel.SailShip}
 */
SailorIO.ClientInputModel.SailShip.getRootAsSailShip = function(bb, obj) {
  return (obj || new SailorIO.ClientInputModel.SailShip).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
SailorIO.ClientInputModel.SailShip.startSailShip = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SailorIO.ClientInputModel.SailShip.endSailShip = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SailorIO.ClientInputModel.GetWorldInfo = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SailorIO.ClientInputModel.GetWorldInfo}
 */
SailorIO.ClientInputModel.GetWorldInfo.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SailorIO.ClientInputModel.GetWorldInfo=} obj
 * @returns {SailorIO.ClientInputModel.GetWorldInfo}
 */
SailorIO.ClientInputModel.GetWorldInfo.getRootAsGetWorldInfo = function(bb, obj) {
  return (obj || new SailorIO.ClientInputModel.GetWorldInfo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
SailorIO.ClientInputModel.GetWorldInfo.startGetWorldInfo = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SailorIO.ClientInputModel.GetWorldInfo.endGetWorldInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SailorIO.ClientInputModel.NewPlayer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SailorIO.ClientInputModel.NewPlayer}
 */
SailorIO.ClientInputModel.NewPlayer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SailorIO.ClientInputModel.NewPlayer=} obj
 * @returns {SailorIO.ClientInputModel.NewPlayer}
 */
SailorIO.ClientInputModel.NewPlayer.getRootAsNewPlayer = function(bb, obj) {
  return (obj || new SailorIO.ClientInputModel.NewPlayer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SailorIO.ClientInputModel.NewPlayer.prototype.accessToken = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SailorIO.ClientInputModel.NewPlayer.startNewPlayer = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} accessTokenOffset
 */
SailorIO.ClientInputModel.NewPlayer.addAccessToken = function(builder, accessTokenOffset) {
  builder.addFieldOffset(0, accessTokenOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SailorIO.ClientInputModel.NewPlayer.endNewPlayer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SailorIO.ClientInputModel.ClientInput = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SailorIO.ClientInputModel.ClientInput}
 */
SailorIO.ClientInputModel.ClientInput.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SailorIO.ClientInputModel.ClientInput=} obj
 * @returns {SailorIO.ClientInputModel.ClientInput}
 */
SailorIO.ClientInputModel.ClientInput.getRootAsClientInput = function(bb, obj) {
  return (obj || new SailorIO.ClientInputModel.ClientInput).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {SailorIO.ClientInputModel.ClientEventTypes}
 */
SailorIO.ClientInputModel.ClientInput.prototype.EventType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {SailorIO.ClientInputModel.ClientEventTypes} */ (this.bb.readUint8(this.bb_pos + offset)) : SailorIO.ClientInputModel.ClientEventTypes.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
SailorIO.ClientInputModel.ClientInput.prototype.Event = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SailorIO.ClientInputModel.ClientInput.startClientInput = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {SailorIO.ClientInputModel.ClientEventTypes} EventType
 */
SailorIO.ClientInputModel.ClientInput.addEventType = function(builder, EventType) {
  builder.addFieldInt8(0, EventType, SailorIO.ClientInputModel.ClientEventTypes.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} EventOffset
 */
SailorIO.ClientInputModel.ClientInput.addEvent = function(builder, EventOffset) {
  builder.addFieldOffset(1, EventOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SailorIO.ClientInputModel.ClientInput.endClientInput = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
SailorIO.ClientInputModel.ClientInput.finishClientInputBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.SailorIO = SailorIO;
